name: VoidTP
version: 1.1
main: nl.jessegeerts.customplugins.voidtp.Main
commands:
  voidtpreload:
    usage: /<command>
    description: Reload voidtp
  setvoidspawn:
    usage: /<command>
    description: Set the Spawn
